name: Publish Docker image
on:
  push:
    paths:
      - Cargo.toml
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          file: ./dockerfiles/testing/slim/Dockerfile
          repository: yabirgb/bukhgalter
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          file: ./dockerfiles/testing/slim/Dockerfile
          repository: yabirgb/bukhgalter/bukhgalter-testing
          tag_with_ref: true
