name: Publish Docker image
on: push
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ./dockerfiles/alpine/Dockerfile
          repository: yabirgb/bukhgalter
          tag_with_ref: true
          cache-from: type=registry,ref=yabirgb/bukhgalter:latest
          cache-to: type=inline
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./dockerfiles/alpine/Dockerfile
          repository: yabirgb/bukhgalter/bukhgalter-image
          tag_with_ref: true
