on: push

name: Testing workflow

jobs:

  # Detectar si algun archivo clave ha sido modificado
  # basado en https://github.com/dorny/paths-filter
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.deepChanges.outputs.files }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: deepChanges
        with:
          filters: |
            core:
              - 'dockerfiles/**'
              - 'Cargo.toml'
              - '.github/**'

  rebuildContainer:
    needs: changes
    runs-on: ubuntu-latest
    if: always() && ${{ needs.changes.outputs.core == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfiles/testing/slim/Dockerfile
          repository: yabirgb/bukhgalter
          tag_with_ref: true

  test:
    needs: [changes, rebuildContainer]
    if: "always()"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test