on: push

name: Testing workflow
env:
  TEST_CONTAINER: yabirgb/bukhgalter:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
      - name: Check out the repo
        run: docker run -t -v `pwd`:/test yabirgb/bukhgalter:latest

